# Generated by Django 4.2 on 2025-11-17 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretitem',
            name='content_encrypted',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='secretitem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dek_encrypted', models.BinaryField(blank=True, null=True)),
                ('dek_salt', models.BinaryField(blank=True, null=True)),
                ('dek_kdf_iterations', models.IntegerField(default=200000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
